# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      tooling:
        patterns:
          - "neostandard"
          - "npm-run-all2"
          - "releasearoni"
      typescript:
        patterns:
          - "typescript"
          - "@types/node"
          - "@voxpelli/tsconfig"
      playwright:
        patterns:
          - "@playwright/test"
      postcss:
        patterns:
          - "postcss"
          - "postcss-*"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1
