name: tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node }}
    - name: npm install && npm test
      run: |
        npm i
        npm test
